// <auto-generated />
using System;
using BlueChallenge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueChallenge.Api.Migrations
{
    [DbContext(typeof(BlueChallengeDbContext))]
    partial class BlueChallengeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BlueChallenge.Api.Model.Schedule.ScheduleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("BlueChallenge.Api.Model.User.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlueChallenge.Api.Model.Schedule.ScheduleModel", b =>
                {
                    b.HasOne("BlueChallenge.Api.Model.User.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BlueChallenge.Api.Model.Utils.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("ScheduleModelId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("End")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("TEXT");

                            b1.HasKey("ScheduleModelId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleModelId");
                        });

                    b.OwnsOne("BlueChallenge.Api.Model.Utils.HourRange", "HourRange", b1 =>
                        {
                            b1.Property<Guid>("ScheduleModelId")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("TEXT");

                            b1.HasKey("ScheduleModelId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleModelId");
                        });

                    b.Navigation("DateRange")
                        .IsRequired();

                    b.Navigation("HourRange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlueChallenge.Api.Model.User.UserModel", b =>
                {
                    b.OwnsOne("BlueChallenge.Api.Model.User.UserCredentialsModel", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("UserModelId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("UserModelId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserModelId");

                            b1.OwnsOne("BlueChallenge.Api.Model.User.EmailModel", "Email", b2 =>
                                {
                                    b2.Property<Guid>("UserCredentialsModelUserModelId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Alias")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Provider")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("UserCredentialsModelUserModelId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserCredentialsModelUserModelId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();
                        });

                    b.OwnsOne("BlueChallenge.Api.Model.User.UserPersonalInfoModel", "PersonalInfo", b1 =>
                        {
                            b1.Property<Guid>("UserModelId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.HasKey("UserModelId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserModelId");

                            b1.OwnsMany("BlueChallenge.Api.Model.User.EmailModel", "Emails", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Alias")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Provider")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("UserId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("Users_Emails");

                                    b2.WithOwner()
                                        .HasForeignKey("UserId");
                                });

                            b1.OwnsOne("BlueChallenge.Api.Model.User.PhoneModel", "Phone", b2 =>
                                {
                                    b2.Property<Guid>("UserPersonalInfoModelUserModelId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DDD")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(9)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("UserPersonalInfoModelUserModelId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserPersonalInfoModelUserModelId");
                                });

                            b1.Navigation("Emails");

                            b1.Navigation("Phone")
                                .IsRequired();
                        });

                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("PersonalInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
